

// Tests generated by Scribe at 09/27/2019 22:30:58. 
// You no touchee.
using Scribe.xUnit;

namespace Scribe.Tests.xUnit
{
	public partial class TheFizzBuzzPlayer
	{
		[NamedFact("given 1 returns 1")] public void Given1_Returns1() => Run(0);
		[NamedFact("given 2 returns 2")] public void Given2_Returns2() => Run(1);
		[NamedFact("given 3 returns fizz")] public void Given3_ReturnsFizz() => Run(2);
		[NamedFact("given 5 returns buzz")] public void Given5_ReturnsBuzz() => Run(3);
		[NamedFact("given 9 returns fizz")] public void Given9_ReturnsFizz() => Run(4);
		[NamedFact("given 10 returns buzz")] public void Given10_ReturnsBuzz() => Run(5);
		[NamedFact("given 15 returns fizzbuzz")] public void Given15_ReturnsFizzbuzz() => Run(6);
		[NamedFact("given 90 returns fizzbuzz")] public void Given90_ReturnsFizzbuzz() => Run(7);
		[NamedFact("when playing a 5 logs the play")] public void WhenPlayingA5_LogsThePlay() => Run(8);
		[NamedFact("when playing a 7 logs the play")] public void WhenPlayingA7_LogsThePlay() => Run(9);
	}
}

