// Tests generated by Scribe at 09/14/2018 20:27:44. 
// You no touchee.
using NUnit.Framework;

namespace Tests.NUnit
{
	[TestFixture]
	public partial class TheFizzBuzzPlayer
	{
		[TestCase(TestName = "given 1 returns 1")] public void Given1_Returns1() => Run(0);
		[TestCase(TestName = "given 2 returns 2")] public void Given2_Returns2() => Run(1);
		[TestCase(TestName = "given 3 returns fizz")] public void Given3_ReturnsFizz() => Run(2);
		[TestCase(TestName = "given 5 returns buzz")] public void Given5_ReturnsBuzz() => Run(3);
		[TestCase(TestName = "given 9 returns fizz")] public void Given9_ReturnsFizz() => Run(4);
		[TestCase(TestName = "given 10 returns buzz")] public void Given10_ReturnsBuzz() => Run(5);
		[TestCase(TestName = "given 15 returns fizzbuzz")] public void Given15_ReturnsFizzbuzz() => Run(6);
		[TestCase(TestName = "given 90 returns fizzbuzz")] public void Given90_ReturnsFizzbuzz() => Run(7);
		[TestCase(TestName = "when playing a 5 logs the play")] public void WhenPlayingA5_LogsThePlay() => Run(8);
		[TestCase(TestName = "when playing a 7 logs the play")] public void WhenPlayingA7_LogsThePlay() => Run(9);
	}
}

namespace Tests.NUnit.Romans
{
	[TestFixture]
	public partial class TheRomanNumeralCalculator
	{
		[TestCase(TestName = "when adding I and I returns II")] public void WhenAddingIAndI_ReturnsIi() => Run(0);
		[TestCase(TestName = "when adding I and II returns III")] public void WhenAddingIAndIi_ReturnsIii() => Run(1);
		[TestCase(TestName = "when adding I and III returns IV")] public void WhenAddingIAndIii_ReturnsIv() => Run(2);
	}
}

