// Tests generated by Scribe at 09/14/2018 20:27:45. 
// You no touchee.
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Tests.MSTest
{
	[TestClass]
	public partial class TheFizzBuzzPlayer
	{
		[TestMethod] public void Given1_Returns1() => Run(0);
		[TestMethod] public void Given2_Returns2() => Run(1);
		[TestMethod] public void Given3_ReturnsFizz() => Run(2);
		[TestMethod] public void Given5_ReturnsBuzz() => Run(3);
		[TestMethod] public void Given9_ReturnsFizz() => Run(4);
		[TestMethod] public void Given10_ReturnsBuzz() => Run(5);
		[TestMethod] public void Given15_ReturnsFizzbuzz() => Run(6);
		[TestMethod] public void Given90_ReturnsFizzbuzz() => Run(7);
		[TestMethod] public void WhenPlayingA5_LogsThePlay() => Run(8);
		[TestMethod] public void WhenPlayingA7_LogsThePlay() => Run(9);
	}
}

namespace Tests.MSTest.Romans
{
	[TestClass]
	public partial class TheRomanNumeralCalculator
	{
		[TestMethod] public void WhenAddingIAndI_ReturnsIi() => Run(0);
		[TestMethod] public void WhenAddingIAndIi_ReturnsIii() => Run(1);
		[TestMethod] public void WhenAddingIAndIii_ReturnsIv() => Run(2);
	}
}

